(defvar tc 0)
(defvar n 0)
(defvar a 0)
(defvar b 0)
(defvar ans 0)
(setf tc (read))
(loop for i from 1 to tc do
	(setf n (read))
	(setf a (read))
	(setf ans a)
	(loop for j from 2 to n do
		(setf b (read))
		(if (< a b)
			(setf ans (+ ans (- b a)))
		)
		(setf a b)
	)
	(format t "~D~%" ans)
	; (write ans)
	; (terpri)
)